[application]

[bundle]
identifier = "com.operon.dioxus"
publisher = "Operon"
copyright = "Copyright (c) 2026 Operon"
category = "Productivity"
short_description = "Operon — local-first notes editor"
long_description = "Operon-dioxus is a local-first, project-aware notes editor."

[web.app]

# HTML title tag content
title = "operon-dioxus"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
