//! Unix-socket-listening bridge server.
//!
//! `Server::serve` binds the socket, then accepts connections in a
//! loop. Each connection runs in its own task and is gated on the
//! `operon/hello` handshake. After hello succeeds the connection
//! enters an MCP-frame dispatch loop — see [`dispatch`].
//!
//! Lifetime
//! --------
//! The server runs until [`ServerHandle::shutdown`] is called or the
//! task is dropped. On shutdown the socket file is unlinked so a
//! restart of the GUI can reclaim the same path.
//!
//! Concurrency
//! -----------
//! Each accepted connection runs independently. Within one connection
//! the bridge dispatches every incoming `tools/call` as its own task
//! and funnels replies back through a single writer task — so a slow
//! handler doesn't block the read loop or block sibling calls on the
//! same connection. Tool handlers therefore see overlapping calls
//! both across and within connections; they are responsible for their
//! own internal locking.

#![cfg(unix)]

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{json, Value};
use thiserror::Error;
use tokio::io::{AsyncWriteExt, BufReader};
use tokio::net::{UnixListener, UnixStream};
use tokio::sync::{mpsc, watch, Mutex};
use tokio::task::JoinSet;
use tracing::{debug, error, info, warn};

use crate::protocol::{read_frame, write_frame, Frame};
use crate::{BridgeError, Result};

/// Server-side handler for one MCP tool. The bridge wraps these as
/// `tools/list` entries and dispatches `tools/call` requests by name.
#[async_trait]
pub trait ToolHandler: Send + Sync + 'static {
    /// Tool name as exposed to Claude. By convention this is
    /// `operon_<verb>` (snake_case) so `mcp__operon__<name>` shows up
    /// in Claude's tool list with the server prefix it auto-derives
    /// from the `.mcp.json` entry name.
    fn name(&self) -> &str;

    /// Free-text description that ends up in the MCP `tools/list`
    /// response. Claude reads this to decide when to call the tool —
    /// keep it specific.
    fn description(&self) -> &str;

    /// JSON Schema for the tool's input. The MCP spec requires this;
    /// Claude refuses to call tools without a schema.
    fn input_schema(&self) -> Value;

    /// Execute the call. Return the MCP `content` payload (a
    /// `Vec<{ type, text }>`-shaped Value) — the server wraps it in
    /// the response envelope.
    async fn call(&self, args: Value) -> std::result::Result<Value, ToolHandlerError>;
}

/// Error returned by a tool handler. The bridge surfaces these as MCP
/// `isError: true` tool_result frames so Claude can recover.
#[derive(Debug, Error)]
#[error("{message}")]
pub struct ToolHandlerError {
    pub message: String,
}

impl ToolHandlerError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl From<String> for ToolHandlerError {
    fn from(s: String) -> Self {
        Self::new(s)
    }
}

impl From<&str> for ToolHandlerError {
    fn from(s: &str) -> Self {
        Self::new(s)
    }
}

/// Bundle of everything `Server::serve` needs. Built incrementally
/// with `register_tool` before `.serve()` consumes it.
pub struct Server {
    sock_path: PathBuf,
    /// UUID generated by the GUI on startup. The stub passes it in
    /// the hello frame; the bridge rejects connections that don't
    /// present it. Token is shared across all accepted connections.
    token: String,
    tools: HashMap<String, Arc<dyn ToolHandler>>,
}

impl Server {
    pub fn new(sock_path: impl Into<PathBuf>, token: impl Into<String>) -> Self {
        Self {
            sock_path: sock_path.into(),
            token: token.into(),
            tools: HashMap::new(),
        }
    }

    /// Add a tool to the server's dispatch table. Panics on duplicate
    /// name — registration is a startup-time API; collisions are bugs.
    pub fn register_tool(mut self, handler: Arc<dyn ToolHandler>) -> Self {
        let name = handler.name().to_string();
        if self.tools.contains_key(&name) {
            panic!("operon-bridge: duplicate tool name {name:?}");
        }
        self.tools.insert(name, handler);
        self
    }

    pub fn socket_path(&self) -> &Path {
        &self.sock_path
    }

    pub fn token(&self) -> &str {
        &self.token
    }

    /// Bind the socket and start accepting. Runs until `handle.shutdown()`
    /// is called or the returned future is dropped.
    pub async fn serve(self) -> Result<ServerHandle> {
        // Best-effort cleanup of a stale socket from a prior crashed
        // process. `bind` would otherwise fail with EADDRINUSE — the
        // file persists on disk after the previous owner died.
        let _ = tokio::fs::remove_file(&self.sock_path).await;

        let listener = UnixListener::bind(&self.sock_path)?;
        // Tighten permissions immediately. We rely on filesystem
        // perms (mode 600) plus the token to authenticate — on a
        // shared host this prevents another user from probing the
        // socket.
        set_socket_permissions(&self.sock_path)?;

        let (shutdown_tx, shutdown_rx) = watch::channel(false);
        let tools = Arc::new(self.tools);
        let sock_path_for_cleanup = self.sock_path.clone();
        let token = Arc::new(self.token);

        let accept_task = tokio::spawn({
            let mut shutdown_rx = shutdown_rx.clone();
            async move {
                info!(socket = %sock_path_for_cleanup.display(), "operon-bridge accepting");
                loop {
                    tokio::select! {
                        biased;
                        _ = shutdown_rx.changed() => {
                            if *shutdown_rx.borrow() {
                                break;
                            }
                        }
                        accept = listener.accept() => match accept {
                            Ok((stream, _addr)) => {
                                let tools = Arc::clone(&tools);
                                let token = Arc::clone(&token);
                                let mut sd = shutdown_rx.clone();
                                tokio::spawn(async move {
                                    if let Err(e) = serve_connection(stream, token, tools, &mut sd).await {
                                        // Clean disconnects show up as
                                        // FrameError::Eof bubbled to BridgeError;
                                        // surface anything else.
                                        match &e {
                                            BridgeError::Frame(crate::protocol::FrameError::Eof) => {
                                                debug!("bridge: peer closed");
                                            }
                                            _ => warn!(error = ?e, "bridge connection ended"),
                                        }
                                    }
                                });
                            }
                            Err(e) => {
                                warn!(error = %e, "bridge accept error; continuing");
                            }
                        }
                    }
                }
                info!("operon-bridge accept loop exiting");
                let _ = tokio::fs::remove_file(&sock_path_for_cleanup).await;
            }
        });

        Ok(ServerHandle {
            shutdown_tx,
            task: Mutex::new(Some(accept_task)),
        })
    }
}

/// Handle returned by `Server::serve`. Drop it to stop accepting new
/// connections (existing ones keep running until their peer hangs
/// up); call `shutdown().await` for a graceful join.
pub struct ServerHandle {
    shutdown_tx: watch::Sender<bool>,
    task: Mutex<Option<tokio::task::JoinHandle<()>>>,
}

impl ServerHandle {
    pub async fn shutdown(&self) {
        let _ = self.shutdown_tx.send(true);
        let task = self.task.lock().await.take();
        if let Some(t) = task {
            let _ = t.await;
        }
    }
}

impl Drop for ServerHandle {
    fn drop(&mut self) {
        let _ = self.shutdown_tx.send(true);
    }
}

async fn serve_connection(
    stream: UnixStream,
    token: Arc<String>,
    tools: Arc<HashMap<String, Arc<dyn ToolHandler>>>,
    shutdown_rx: &mut watch::Receiver<bool>,
) -> Result<()> {
    let (read_half, mut write_half) = stream.into_split();
    let mut reader = BufReader::new(read_half);

    // === Hello / auth ===
    // First frame MUST be `operon/hello` with a matching token. We
    // reject anything else — including a well-formed MCP frame — so
    // a process that connects to the socket "by accident" doesn't
    // get a tool/list response.
    let hello = read_frame(&mut reader).await?;
    let method = hello.raw.get("method").and_then(|v| v.as_str());
    if method != Some("operon/hello") {
        let id = hello.raw.get("id").cloned().unwrap_or(Value::Null);
        let _ = write_frame(
            &mut write_half,
            &Frame::error(id, -32_001, "expected operon/hello first"),
        )
        .await;
        return Err(BridgeError::Auth("first frame was not operon/hello".into()));
    }
    let presented = hello
        .raw
        .get("params")
        .and_then(|p| p.get("token"))
        .and_then(|t| t.as_str())
        .unwrap_or("");
    if !ct_eq(presented.as_bytes(), token.as_bytes()) {
        let id = hello.raw.get("id").cloned().unwrap_or(Value::Null);
        let _ = write_frame(
            &mut write_half,
            &Frame::error(id, -32_002, "bad token"),
        )
        .await;
        // Don't reveal the expected token; just deny.
        return Err(BridgeError::Auth("hello token mismatch".into()));
    }
    let id = hello.raw.get("id").cloned().unwrap_or(Value::Null);
    write_frame(
        &mut write_half,
        &Frame::result(
            id,
            json!({
                "ok": true,
                "server": "operon-bridge/0.1",
            }),
        ),
    )
    .await?;
    write_half.flush().await.ok();

    // === Writer task ===
    // Takes ownership of `write_half` from here on. Every outbound
    // frame goes through `write_tx`. We serialize writes (the
    // OwnedWriteHalf can't be shared, and JSON-RPC framing requires
    // each frame to land atomically on the wire) but NOT executions.
    let (write_tx, mut write_rx) = mpsc::unbounded_channel::<Frame>();
    let writer_task = tokio::spawn(async move {
        while let Some(frame) = write_rx.recv().await {
            if write_frame(&mut write_half, &frame).await.is_err() {
                // Peer hung up — stop draining. The reader half will
                // see EOF on its next read and tear down the loop.
                break;
            }
            write_half.flush().await.ok();
        }
    });

    // === MCP frame loop ===
    // Each request runs in its own task so a slow `tools/call`
    // doesn't block the read loop or sibling calls on this
    // connection. Replies fan back through `write_tx` in completion
    // order; Claude tracks request ↔ reply matching via the JSON-RPC
    // `id` field, so out-of-order completion is fine.
    let mut handlers: JoinSet<()> = JoinSet::new();
    let outcome: Result<()> = loop {
        tokio::select! {
            biased;
            _ = shutdown_rx.changed() => {
                if *shutdown_rx.borrow() {
                    break Err(BridgeError::Shutdown);
                }
            }
            frame = read_frame(&mut reader) => {
                let frame = match frame {
                    Ok(f) => f,
                    Err(e) => break Err(e.into()),
                };
                let tools = Arc::clone(&tools);
                let write_tx = write_tx.clone();
                handlers.spawn(async move {
                    if let Some(reply) = dispatch(&frame, &tools).await {
                        // Send-Err just means the writer task already
                        // exited (peer hung up); drop the reply.
                        let _ = write_tx.send(reply);
                    }
                    // Notifications (no `id` field) produce no reply.
                });
            }
        }
    };

    // Tear down: abort any in-flight handler tasks (their replies
    // would have nowhere to go after the writer drops), then close
    // the write channel so the writer task drains and exits.
    handlers.shutdown().await;
    drop(write_tx);
    let _ = writer_task.await;
    outcome
}

/// Constant-time byte compare. Tokens are short, but use this anyway
/// — it costs nothing and keeps any future bigger-token migration
/// off the timing-attack list.
fn ct_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff: u8 = 0;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

/// Dispatch one MCP request to the right handler. Returns `None` for
/// notifications (no `id`) — the caller doesn't write a reply for those.
async fn dispatch(
    frame: &Frame,
    tools: &Arc<HashMap<String, Arc<dyn ToolHandler>>>,
) -> Option<Frame> {
    let method = frame.raw.get("method").and_then(|v| v.as_str())?;
    let id = frame.raw.get("id").cloned();

    // Notifications don't carry an id and don't get a reply.
    let id = match id {
        Some(v) if !v.is_null() => v,
        _ => {
            // Drop notifications silently — MCP `notifications/initialized`
            // arrives here after `initialize` and is intentionally fire-
            // and-forget.
            return None;
        }
    };

    match method {
        "initialize" => Some(Frame::result(
            id,
            json!({
                "protocolVersion": "2024-11-05",
                "capabilities": {
                    "tools": { "listChanged": false },
                },
                "serverInfo": { "name": "operon-bridge", "version": "0.1.0" },
            }),
        )),
        "tools/list" => {
            let list: Vec<Value> = tools
                .values()
                .map(|t| {
                    json!({
                        "name": t.name(),
                        "description": t.description(),
                        "inputSchema": t.input_schema(),
                    })
                })
                .collect();
            Some(Frame::result(id, json!({ "tools": list })))
        }
        "tools/call" => {
            let params = frame.raw.get("params").cloned().unwrap_or(Value::Null);
            let name = params
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let args = params.get("arguments").cloned().unwrap_or(Value::Null);
            let Some(handler) = tools.get(&name).cloned() else {
                warn!(tool = %name, "unknown tool requested");
                return Some(Frame::result(
                    id,
                    json!({
                        "isError": true,
                        "content": [{
                            "type": "text",
                            "text": format!("unknown tool: {name}"),
                        }],
                    }),
                ));
            };
            info!(tool = %name, "tools/call dispatching");
            let started = std::time::Instant::now();
            let outcome = handler.call(args).await;
            info!(
                tool = %name,
                elapsed_ms = started.elapsed().as_millis() as u64,
                ok = outcome.is_ok(),
                "tools/call returned"
            );
            match outcome {
                Ok(content) => Some(Frame::result(
                    id,
                    json!({
                        "content": content,
                        "isError": false,
                    }),
                )),
                Err(e) => Some(Frame::result(
                    id,
                    json!({
                        "isError": true,
                        "content": [{
                            "type": "text",
                            "text": e.message,
                        }],
                    }),
                )),
            }
        }
        other => {
            error!(method = other, "unknown MCP method");
            Some(Frame::error(id, -32_601, format!("method not found: {other}")))
        }
    }
}

#[cfg(unix)]
fn set_socket_permissions(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = std::fs::metadata(path)?.permissions();
    perms.set_mode(0o600);
    std::fs::set_permissions(path, perms)
}

#[cfg(test)]
#[cfg(unix)]
mod tests {
    use super::*;
    use tokio::io::{AsyncWriteExt, BufReader};

    struct EchoTool;

    #[async_trait]
    impl ToolHandler for EchoTool {
        fn name(&self) -> &str {
            "operon_echo"
        }
        fn description(&self) -> &str {
            "echo args back verbatim"
        }
        fn input_schema(&self) -> Value {
            json!({ "type": "object", "additionalProperties": true })
        }
        async fn call(&self, args: Value) -> std::result::Result<Value, ToolHandlerError> {
            Ok(json!([{ "type": "text", "text": args.to_string() }]))
        }
    }

    fn temp_sock() -> PathBuf {
        let dir = tempfile::tempdir().unwrap();
        // Path needs to exist for the server bind; tempdir handles cleanup
        // even though we leak it here (test process exits).
        let path = dir.path().join("bridge.sock");
        std::mem::forget(dir);
        path
    }

    #[tokio::test]
    async fn handshake_succeeds_with_matching_token() {
        let sock = temp_sock();
        let token = uuid::Uuid::new_v4().to_string();
        let server = Server::new(sock.clone(), token.clone()).register_tool(Arc::new(EchoTool));
        let handle = server.serve().await.unwrap();

        let mut stream = tokio::net::UnixStream::connect(&sock).await.unwrap();
        let hello = Frame::new(json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "operon/hello",
            "params": { "token": token, "client": "test/0.1" },
        }));
        write_frame(&mut stream, &hello).await.unwrap();
        stream.flush().await.unwrap();

        let (r, _w) = stream.into_split();
        let mut buf = BufReader::new(r);
        let reply = read_frame(&mut buf).await.unwrap();
        assert_eq!(reply.raw["result"]["ok"], true);
        assert_eq!(reply.raw["id"], 1);

        handle.shutdown().await;
    }

    #[tokio::test]
    async fn handshake_rejects_bad_token() {
        let sock = temp_sock();
        let token = uuid::Uuid::new_v4().to_string();
        let server = Server::new(sock.clone(), token);
        let handle = server.serve().await.unwrap();

        let mut stream = tokio::net::UnixStream::connect(&sock).await.unwrap();
        let hello = Frame::new(json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "operon/hello",
            "params": { "token": "wrong", "client": "test/0.1" },
        }));
        write_frame(&mut stream, &hello).await.unwrap();
        stream.flush().await.unwrap();

        let (r, _w) = stream.into_split();
        let mut buf = BufReader::new(r);
        let reply = read_frame(&mut buf).await.unwrap();
        assert!(reply.raw.get("error").is_some(), "expected error, got {reply:?}");

        // Server should have closed the socket; next read is EOF.
        match read_frame(&mut buf).await {
            Err(crate::protocol::FrameError::Eof) => {}
            other => panic!("expected EOF after bad-token rejection, got {other:?}"),
        }

        handle.shutdown().await;
    }

    #[tokio::test]
    async fn tools_list_after_handshake() {
        let sock = temp_sock();
        let token = uuid::Uuid::new_v4().to_string();
        let server = Server::new(sock.clone(), token.clone()).register_tool(Arc::new(EchoTool));
        let handle = server.serve().await.unwrap();

        let mut stream = tokio::net::UnixStream::connect(&sock).await.unwrap();
        write_frame(
            &mut stream,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 1, "method": "operon/hello",
                "params": { "token": token, "client": "test" },
            })),
        )
        .await
        .unwrap();
        stream.flush().await.unwrap();

        // Drain hello reply, then ask for tools/list.
        let (r, mut w) = stream.into_split();
        let mut buf = BufReader::new(r);
        let _hello_reply = read_frame(&mut buf).await.unwrap();

        write_frame(
            &mut w,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 2, "method": "tools/list",
            })),
        )
        .await
        .unwrap();
        w.flush().await.unwrap();

        let list = read_frame(&mut buf).await.unwrap();
        let tools = list.raw["result"]["tools"].as_array().expect("array");
        assert_eq!(tools.len(), 1);
        assert_eq!(tools[0]["name"], "operon_echo");

        handle.shutdown().await;
    }

    #[tokio::test]
    async fn tools_call_dispatches_to_handler() {
        let sock = temp_sock();
        let token = uuid::Uuid::new_v4().to_string();
        let server = Server::new(sock.clone(), token.clone()).register_tool(Arc::new(EchoTool));
        let handle = server.serve().await.unwrap();

        let mut stream = tokio::net::UnixStream::connect(&sock).await.unwrap();
        write_frame(
            &mut stream,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 1, "method": "operon/hello",
                "params": { "token": token, "client": "test" },
            })),
        )
        .await
        .unwrap();
        stream.flush().await.unwrap();
        let (r, mut w) = stream.into_split();
        let mut buf = BufReader::new(r);
        let _ = read_frame(&mut buf).await.unwrap();

        write_frame(
            &mut w,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 2,
                "method": "tools/call",
                "params": { "name": "operon_echo", "arguments": { "x": 1 } },
            })),
        )
        .await
        .unwrap();
        w.flush().await.unwrap();

        let reply = read_frame(&mut buf).await.unwrap();
        assert_eq!(reply.raw["result"]["isError"], false);
        let text = reply.raw["result"]["content"][0]["text"]
            .as_str()
            .unwrap()
            .to_string();
        assert!(text.contains("\"x\":1"), "echo body was {text}");

        handle.shutdown().await;
    }

    #[tokio::test]
    async fn unknown_tool_returns_is_error() {
        let sock = temp_sock();
        let token = uuid::Uuid::new_v4().to_string();
        let server = Server::new(sock.clone(), token.clone());
        let handle = server.serve().await.unwrap();

        let mut stream = tokio::net::UnixStream::connect(&sock).await.unwrap();
        write_frame(
            &mut stream,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 1, "method": "operon/hello",
                "params": { "token": token, "client": "test" },
            })),
        )
        .await
        .unwrap();
        stream.flush().await.unwrap();
        let (r, mut w) = stream.into_split();
        let mut buf = BufReader::new(r);
        let _ = read_frame(&mut buf).await.unwrap();

        write_frame(
            &mut w,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 2,
                "method": "tools/call",
                "params": { "name": "operon_nope", "arguments": {} },
            })),
        )
        .await
        .unwrap();
        w.flush().await.unwrap();

        let reply = read_frame(&mut buf).await.unwrap();
        assert_eq!(reply.raw["result"]["isError"], true);

        handle.shutdown().await;
    }

    /// A slow tool handler must NOT block a fast call on the same
    /// connection. Regression test for the original "all RUNNING for
    /// 1m29s" bug: when dispatch was awaited inline in the read
    /// loop, every tool call serialized behind the previous one even
    /// though Claude sent them in parallel.
    #[tokio::test]
    async fn slow_call_does_not_block_fast_call_on_same_connection() {
        use std::time::Duration;

        struct SlowTool;
        #[async_trait]
        impl ToolHandler for SlowTool {
            fn name(&self) -> &str { "slow" }
            fn description(&self) -> &str { "sleeps for 500ms" }
            fn input_schema(&self) -> Value {
                json!({ "type": "object", "additionalProperties": true })
            }
            async fn call(&self, _args: Value) -> std::result::Result<Value, ToolHandlerError> {
                tokio::time::sleep(Duration::from_millis(500)).await;
                Ok(json!([{ "type": "text", "text": "slow done" }]))
            }
        }

        let sock = temp_sock();
        let token = uuid::Uuid::new_v4().to_string();
        let server = Server::new(sock.clone(), token.clone())
            .register_tool(Arc::new(SlowTool))
            .register_tool(Arc::new(EchoTool));
        let handle = server.serve().await.unwrap();

        let mut stream = tokio::net::UnixStream::connect(&sock).await.unwrap();
        write_frame(
            &mut stream,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 0, "method": "operon/hello",
                "params": { "token": token, "client": "test" },
            })),
        )
        .await
        .unwrap();
        stream.flush().await.unwrap();
        let (r, mut w) = stream.into_split();
        let mut buf = BufReader::new(r);
        let _ = read_frame(&mut buf).await.unwrap();

        // Fire the slow call first, then the echo immediately after.
        // With inline-await dispatch, the echo reply would wait the
        // full 500ms. With per-call task spawning it should come
        // back almost instantly.
        write_frame(
            &mut w,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 1,
                "method": "tools/call",
                "params": { "name": "slow", "arguments": {} },
            })),
        )
        .await
        .unwrap();
        write_frame(
            &mut w,
            &Frame::new(json!({
                "jsonrpc": "2.0", "id": 2,
                "method": "tools/call",
                "params": { "name": "operon_echo", "arguments": { "fast": true } },
            })),
        )
        .await
        .unwrap();
        w.flush().await.unwrap();

        let start = std::time::Instant::now();
        let first = read_frame(&mut buf).await.unwrap();
        let first_elapsed = start.elapsed();
        let second = read_frame(&mut buf).await.unwrap();

        // The echo should return first (it completes in <1ms; the
        // slow tool sleeps 500ms), and well under the slow tool's
        // wall-time. 200ms is plenty of slack for CI noise.
        assert_eq!(
            first.raw["id"], 2,
            "echo (id=2) should finish first; got id={:?}",
            first.raw["id"]
        );
        assert_eq!(second.raw["id"], 1, "slow (id=1) should arrive second");
        assert!(
            first_elapsed < Duration::from_millis(200),
            "echo reply took {first_elapsed:?} — slow call is blocking the read loop"
        );

        handle.shutdown().await;
    }
}
