#!/usr/bin/env node

/**
 * coverage-checker.js — Documentation coverage analyzer
 *
 * Scans the repository for modules, APIs, tables, and env vars,
 * then checks if they are documented in the instructions/ folder.
 *
 * Usage:
 *   node instructions/automation/coverage-checker.js [--ci]
 *
 * Options:
 *   --ci   Exit with code 1 if coverage is below 100%
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const INSTRUCTIONS = path.resolve(__dirname, '..');
const REPORT_PATH = path.join(INSTRUCTIONS, 'coverage-report.md');

// --- Helpers ---

function readFile(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch {
    return '';
  }
}

function listDir(dirPath, opts = {}) {
  try {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    return entries
      .filter(e => opts.dirs ? e.isDirectory() : opts.files ? e.isFile() : true)
      .map(e => e.name);
  } catch {
    return [];
  }
}

function searchInDocs(term) {
  const mdFiles = listDir(INSTRUCTIONS, { files: true }).filter(f => f.endsWith('.md'));
  for (const file of mdFiles) {
    const content = readFile(path.join(INSTRUCTIONS, file));
    if (content.includes(term)) return file;
  }

  // Also check subdirectories
  const subDirs = ['diagrams', 'templates'];
  for (const dir of subDirs) {
    const subFiles = listDir(path.join(INSTRUCTIONS, dir), { files: true })
      .filter(f => f.endsWith('.md'));
    for (const file of subFiles) {
      const content = readFile(path.join(INSTRUCTIONS, dir, file));
      if (content.includes(term)) return `${dir}/${file}`;
    }
  }

  return null;
}

// --- Scanners ---

function checkCrates() {
  const cratesDir = path.join(ROOT, 'crates');
  const crates = listDir(cratesDir, { dirs: true });
  const results = [];

  for (const crate of crates) {
    const found = searchInDocs(crate);
    results.push({
      name: crate,
      documented: !!found,
      location: found,
    });
  }

  return results;
}

function checkApiRoutes() {
  const routesDir = path.join(ROOT, 'crates', 'operon-api-server', 'src', 'routes');
  const routes = listDir(routesDir, { files: true })
    .filter(f => f.endsWith('.rs'))
    .map(f => f.replace('.rs', ''));

  const results = [];
  for (const route of routes) {
    const apiRef = readFile(path.join(INSTRUCTIONS, 'api-reference.md'));
    const found = apiRef.includes(route) || apiRef.includes(route.replace('_', ' '));
    results.push({
      name: route,
      documented: found,
      location: found ? 'api-reference.md' : null,
    });
  }

  return results;
}

function checkTestFiles() {
  const testsDir = path.join(ROOT, 'tests');
  const tests = listDir(testsDir, { files: true }).filter(f => f.endsWith('.rs'));
  const results = [];

  for (const test of tests) {
    const found = searchInDocs(test.replace('.rs', ''));
    results.push({
      name: test,
      documented: !!found,
      location: found,
    });
  }

  return results;
}

function checkE2ESpecs() {
  const specsDir = path.join(ROOT, 'e2e', 'specs');
  const specs = listDir(specsDir, { files: true }).filter(f => f.endsWith('.spec.ts'));
  const results = [];

  for (const spec of specs) {
    const found = searchInDocs(spec);
    results.push({
      name: spec,
      documented: !!found,
      location: found,
    });
  }

  return results;
}

function checkSetupGuides() {
  const guides = ['setup-guide.md', 'setup-windows.md', 'setup-linux.md', 'setup-macos.md'];
  return guides.map(g => ({
    name: g,
    documented: fs.existsSync(path.join(INSTRUCTIONS, g)),
    location: g,
  }));
}

// --- Report Generator ---

function generateReport(sections) {
  const today = new Date().toISOString().split('T')[0];
  let report = `# Documentation Coverage Report\n\n`;
  report += `> Auto-generated by coverage-checker.js\n\n`;
  report += `*Last checked: ${today}*\n\n---\n\n`;
  report += `## Coverage by Category\n\n`;

  let totalCovered = 0;
  let totalItems = 0;

  for (const [name, items] of Object.entries(sections)) {
    const covered = items.filter(i => i.documented).length;
    const total = items.length;
    totalCovered += covered;
    totalItems += total;
    const pct = total > 0 ? Math.round((covered / total) * 100) : 100;

    report += `### ${name}\n\n`;
    report += `| Item | Documented | Location |\n`;
    report += `|---|---|---|\n`;
    for (const item of items) {
      const status = item.documented ? '✅' : '❌';
      const loc = item.location || '—';
      report += `| \`${item.name}\` | ${status} | ${loc} |\n`;
    }
    report += `\n**Coverage: ${covered}/${total} (${pct}%)**\n\n---\n\n`;
  }

  const totalPct = totalItems > 0 ? Math.round((totalCovered / totalItems) * 100) : 100;
  report += `## Overall Coverage\n\n`;
  report += `| Category | Covered | Total | Percentage |\n`;
  report += `|---|---|---|---|\n`;
  for (const [name, items] of Object.entries(sections)) {
    const covered = items.filter(i => i.documented).length;
    const total = items.length;
    const pct = total > 0 ? Math.round((covered / total) * 100) : 100;
    report += `| ${name} | ${covered} | ${total} | ${pct}% |\n`;
  }
  report += `| **Total** | **${totalCovered}** | **${totalItems}** | **${totalPct}%** |\n`;

  return { report, coverage: totalPct };
}

// --- Main ---

function main() {
  const args = process.argv.slice(2);
  const ciMode = args.includes('--ci');

  console.log('[coverage-checker] Scanning documentation coverage...');

  const sections = {
    'Crates': checkCrates(),
    'API Routes': checkApiRoutes(),
    'Test Files': checkTestFiles(),
    'E2E Specs': checkE2ESpecs(),
    'Setup Guides': checkSetupGuides(),
  };

  const { report, coverage } = generateReport(sections);
  fs.writeFileSync(REPORT_PATH, report, 'utf-8');

  // Summary
  for (const [name, items] of Object.entries(sections)) {
    const covered = items.filter(i => i.documented).length;
    const total = items.length;
    const missing = items.filter(i => !i.documented);
    console.log(`  ${name}: ${covered}/${total}`);
    if (missing.length > 0) {
      for (const m of missing) {
        console.log(`    ❌ ${m.name}`);
      }
    }
  }

  console.log(`\n  Overall: ${coverage}%`);
  console.log(`  Report: ${REPORT_PATH}`);

  if (ciMode && coverage < 100) {
    console.error('\n[coverage-checker] Coverage below 100% — failing CI');
    process.exit(1);
  }
}

main();
